### ISSUE TITLE
WebJobs SDK tutorial should not use global DbContext

### ISSUE THREAD

**Issue by villesinisalo** [Azure/azure-content#2568]
Hello,

I followed the [WebJobs SDK tutorial](http://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-get-started/) and deployed the example project to Azure. However, I believe there is a pretty serious bug with the example code related to using a global DbContext in Program.cs. 

When you create several new ads with images in rapid succession they get queued to the `thumbnailrequest` queue. The WebJob polls once in a minute for new queue messages. If it ever happens to dequeue several messages at once, the following exception immediately gets thrown:

    System.Data.Entity.Core.EntityException: : System.Data.Entity.Core.EntityException: An error occurred while starting a transaction on the provider connection. See the inner exception for details. ---> System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
       at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
       at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
       at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
       at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
       at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
       at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<BeginTransaction>b__0(DbConnection t, BeginTransactionInterceptionContext c)
       at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
       at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.BeginTransaction(DbConnection connection, BeginTransactionInterceptionContext interceptionContext)
       at System.Data.Entity.Core.EntityClient.EntityConnection.<>c__DisplayClassf.<BeginDbTransaction>b__d()
       at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
       at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
       --- End of inner exception stack trace ---
       at System.Data.Entity.Core.EntityClient.EntityConnection.BeginDbTransaction(IsolationLevel isolationLevel)
       at System.Data.Entity.Core.EntityClient.EntityConnection.BeginTransaction()
       at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
       at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
       at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
       at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
       at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
       at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
       at System.Data.Entity.Internal.InternalContext.SaveChanges()
       at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
       at System.Data.Entity.DbContext.SaveChanges()
       at ContosoAdsWebJob.Functions.GenerateThumbnail(BlobInformation blobInfo, Stream input, CloudBlockBlob outputBlob) in c:\Users\user\Documents\Visual Studio 2013\Projects\Simple Azure Website with WebJobs using the WebJobs SDK\C#\ContosoAdsWebJob\Functions.cs:line 36
       at lambda_method(Closure , Object[] )
       at Microsoft.Azure.WebJobs.Host.Executors.VoidInvoker.InvokeAsync(Object[] arguments)
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__23.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithOutputLogsAsync>d__1c.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLogMessageAsync>d__c.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLogMessageAsync>d__c.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__1.MoveNext()

This seems to be related to using a global ContosoAdsContext in `ContosoAdsWebJob.Program`. If one replaces this with a function-scoped `using (ContosoAdsContex db = new ContosoAdsContex()) { ... }` in `ContosoAdsWebJob.Functions.GenerateThumbnail()`, the problem is solved. As it stands, every invocation running in the same WebJob uses the same DbContext, which is bound to lead to a race condition in any production setup since DbContext is not thread-safe.

**Comment by villesinisalo** [comment]
Pinging @tdykstra

**Comment by tdykstra** [comment]
Thanks for reporting that -- I'll fix it.

**Comment by tdykstra** [comment]
Download project is fixed.  Corresponding updates are in the private docs repo, should be live tomorrow.
